### ISSUE TITLE
Build 235 Observations / Recommendations

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#13]
Hi Rick, here are some more comments based on lates build..

1.  Making changes to parameters on couple of tabs does not save when you close the app. For instance, on the devices tab, the chosen focus method does not save when closed if I select focus3. Defaults back to focus2. Same thing on focus tab if I set exposesure to 8, it defaults back to 5 when I open it again.

2. loop count is 100 and only one filter is present but 200 images are being captured. This might be part of the old filter name issue. At first I think it may have had 2 filters in the name space OSC and NoFilter. Once, I connected to the filter which only has NoFilter, I refreashed Humanson and only one filter was present the NoFilter name. I also had  Clear filter set to 1 and focus filter to 0 and LRGB ratio set to one. But, still trys to do 200 images.  Maybe, something to do  with old filter names to be cleared out. 

3. Would be nice to have an abort button on focus tab as I got hung in a loop for some focus runs with 2 and 3 and couldnt get out unless I killed the program.

4. Can there be an option to save the main cameras autodark to a file so it can be selected in Humanson the next time as a file selection so you don't have to travel to scope all the the time for an autodark with the cover and uncover shtick? 

5. This is an old one. When you clearly have a target loaded in the plan and is scheduled, when you hit the image forcast its not the object of interest. Instead, its an older target. You have to manually, down arrow to select it.

**Comment by rrskybox** [comment]
#1  Found the problems.  They will be fixed in the next build.  Let me know if you find anymore of the same.
#2  I'm not able to replicate this.  You should be able to Load the target, Refresh the filters, Set Clear to 0, Focus to 0, LRGB to 1.  You might try this on a fresh target for me.   Let me know.  I'll keep looking at it as well.
#3  Right now, you have to abort the @Focus routines from within TSX.  They are synchronous inside of Humason.  I'll look into why I did that and look to see if I can't make it asynchronous.
#4. If you set AutoDark then TSX only knows one way to do it and that requires a new dark for every new exposure length.  However, a work-around might be to use the Full Reduction.  You could build a calibration library for a small set of short dark frames and apply it to the guider camera.  In a sense, this is exactly what you described.  I can probably walk you through that if you want.  The documentation for the Reduction Group Generator app might help.  
#5  I can't replicate this one either.  On my system, the currently targeted object name is read into the "Target" field, and it's "Assessed".  Maybe you're looking at the "Current Target List"  field?  It will probably be reading the top of the target list, but it's not being applied.

**Comment by astromiester1** [comment]
Hey Rick hope everything is going well... 2 things... 1 bug and one suggestion for improvement.

1. I really think there is a bug in Humanson. If you have  only one filter showing and Set Clear to 1, Focus to 0, LRGB ratio to 1 and you select 60 sec duration with 120 images, the SW tries to do 240.  I have seen this on multiple nights. Let me know if you need any logs or anything...

2. Came up with an idea that would enhance the program.. How about a timer option for the start button to be invoked, so you could set it up after dinner and walk away and it would start the sequence either after timer is up or at a specific time during the night.

Thanks
Dale

**Comment by astromiester1** [comment]
How do I upload a new build.. I ended up doing number 6 above for  a quick delay button feature before the start button gets called.

**Comment by rrskybox** [comment]
2 - I can't replicate this.  Please post a copy of the file or text contents of "<target name>.TargetPlan.xml" from your Documents/Humason directory.  That will give me a better shot at seeing what's going on that might be causing the doubling.

6 - You can already modify the "Start" field in the Target Tab to any start time you'd like.  Doing so will also update the other fields accordingly -- like the Done time.  Imaging will begin within that minute.  You can also write custom executables to run at this start time using the Session Tab.

I'm not sure what you mean by upload a new build.  The current build is in the publish directory (https://github.com/rrskybox/Humason/tree/master/Humason/publish).  I think the current build is in HumasonBuild235.zip.  Are you talking about how to download the whole project?

**Comment by astromiester1** [comment]
Hi Rick...I made a new build I want to share with you withe the start timer.Didnt know I could do this already.Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 3/22/23  4:54 PM  (GMT-05:00) To: rrskybox/Humason ***@***.***> Cc: astromiester1 ***@***.***>, Author ***@***.***> Subject: Re: [rrskybox/Humason] Build 235 Observations / Recommendations (Issue #13) 
2 - I can't replicate this.  Please post a copy of the file or text contents of ".TargetPlan.xml" from your Documents/Humason directory.  That will give me a better shot at seeing what's going on that might be causing the doubling.
6 - You can already modify the "Start" field in the Target Tab to any start time you'd like.  Doing so will also update the other fields accordingly -- like the Done time.  Imaging will begin within that minute.  You can also write custom executables to run at this start time using the Session Tab.
I'm not sure what you mean by upload a new build.  The current build is in the publish directory (https://github.com/rrskybox/Humason/tree/master/Humason/publish).  I think the current build is in HumasonBuild235.zip.  Are you talking about how to download the whole project?

**Comment by astromiester1** [comment]
I compiled a version with my update for the timer on my computer and wanted to share my build with you...

Anyway, don't think target tab works correctly on your current build. I tried M51 target to start tonight at 21:14 and did an update and it reported done is 20:37 with 60sec exposures x 120.

**Comment by astromiester1** [comment]
What is <--> on target tab. No Directions for this...

**Comment by astromiester1** [comment]
[Logs.zip](https://github.com/rrskybox/Humason/files/11045207/Logs.zip)
[Humason.zip](https://github.com/rrskybox/Humason/files/11045212/Humason.zip)

#2. On one of my computers, I notice if unless I use LRGB = 1,  I always get double exposure as calculated by Done with only one clear filter on devices tab and clear filter set to 1. If I set LRGB to 0 and clear filter = 1, I get correct number of exposure prediction on target tab done field.

**Comment by rrskybox** [comment]
The 3/21 log shows M51 being imaged.  I tried out your M51 target plan and found the same doubling effect.  Upon checking, the target file (xml) for M51 shows the selection of two filters for some reason:

         FilterSet
              OSC>0</OSC
              NoFilter>0</NoFilter

Humason doesn't know the difference so it will image two filters (both filter #0's) 120 times, or 240 total images. 
This target needs to be run back through the Devices tab, hit "Refresh" on the filters and choose just one from the filter list.  This should fix the M51 target plan xml file so that only one filter is called out and the expected number of images will be taken.
    
The 3/20 and 3/17 logs show essentially the same thing.  As to the other target plan xml's, the NGC 2359 and NGC 7635 also show the same two filters selected  as above, both 0.  They would be expected to double the image count that you expected.  NCG 2736 and M1 on the other hand appear configured the way you wanted with but one filter configured for imaging.  All that said, I suspect that your default target plan is configured with the same two filters.  To fix that, once you have a corrected plan loaded, select "Save As Default" on the Target tab.

As to the LRGB = 0 test, if you set LRGB to zero then the only image that is shot is the Clear filter. The routine doesn't even look of other selected filters.  Thus, only the Loop number of images will be taken irrespective of how many other filters might be selected for the "RGB" part.  That's why if you have configured two filters to image (as your target plan xml files show), you'll only get one filter (the Clear one) shot for each loop.

As a note, the Clear filter with its index number is only called out separately in order to be able to formulate a loop where you have multiple "clear" images for each set of other filter images.  The way the algorithm works is that, in setting up the sequence, an LRGB number of "clear" filters are shot, then one each of all the other selected filter indices, but not another clear index.  There are certainly a bunch of odd combinations that I haven't tried to test out.  For instance, selecting filters 1-5 for imaging, but choosing filter 0 as the Clear filter index.  I may get around to checking that out someday, but it's just not an expected user set up.

Lastly, the reason that you saw <...> is because it's an artifact of this editor.  Your posted log and target plan files indicate that you figured it out anyway.

**Comment by rrskybox** [comment]
By the way, upon reflection I should note that you do not have to enable (i.e. check) a filter for it to be used for either the focus or clear designations.  It's independent.  The filter enabling is only for the "RGB" part of LRGB.  Clear is for the "L" part.  However, some odd behavior may occur if "Clear" isn't one of the enabled filters as I mentioned in the last post.  "Focus" really doesn't matter at all in that way -- it's just an index.

**Comment by astromiester1** [comment]
So, if I want to use an OSC camera, it appears I really don’t need to have a filter in order to take pictures. Get rid of the filters or uncheck it and keep LRGB to 0 and have no filters wont the image count be singular and work for an OSC camera?

**Comment by rrskybox** [comment]
So... the best way to configure an OSC is to use the SB Filter Wheel simulator and label the first filter to Clear.  Then configure Humason to enable just that filter.  Set Devices Tab->Clear to 0 and Focus to 0.  In the Target tab, set LRGB to 1.  This will give the correct number of images and manage the virtual filter changes.  I have modified the LRGB field to prevent any numbers lower than 1.  You will also need to make sure that the automated image link settings have the name of this first filter as its designated filter as well.

I did find some odd behaviors (i.e. bugs) associated with trying to run no filters.  At some point in time SB must have modified the CLS (and TPoint) configuration such that the filter to be used is configured using a name rather than an index.  I implemented some work-arounds to deal with that.  I will look into removing the need for a simulated filter device at all for OSC, but that may require some architectural change so I have to be careful not to break something else.  In addition, TSX occasionally runs differently when using automation than manually and I have to watch out for that.   I'll let you know.

Latest 64bit version is Build 237

**Comment by rrskybox** [comment]
I had some time this afternoon to spend looking at the "No Filter Wheel" case.  After some rummaging around in the code I finally settled on a pretty clean solution for your OSC situation, such that you do not have to use the TSX Filter Wheel Simulator to run an OSC.

In the most recent build (238), there is now a field under Options for No Filter Wheel.  If you check this, then several things happen:
1. When you hit the Refresh button in the filter area of the Device tab, only one filter will pop up and its name will be "NSW".  In addition, if you had any filters already configured for the current target, they will be cleared out.  You will have to re-select the filters you want.  If "NSW" is the filter, you will need to check it to have any images sequenced.
2. In the Target tab, LRGBRatio is fixed to a minimum of 1.  If you have fewer than two filters configured in the Devices tab, then Humason will not allow you to set the LRGBRatio to anything other than 1.  It will also not select to less than 1.
3. The same behavior will occur if a Filter Wheel is set up in TSX, but will not connect for some reason.
4. If you change the Filter Wheel in TSX, hitting Refresh will allow you to configure its filters to the currently loaded target.
5. As before, the filter that TSX will use for CLS must be selected by name in the Image Link -> Automated Image Link Settings.  If you modify filter names in TSX, you will have recheck to see that this configuration is correct.

I have tested these changes using the simulators to a reasonable extent, but not exhaustively.  Please open another issue if you run into a problem.  I'm going to close this issue as it's gotten too long to make sense anymore.

**Comment by astromiester1** [comment]
Sweet Rick, I will check it out this afternoon… Got a new AP mount I mounting on a pier today… Tried the script last night remotely as I had to attend my wife and sons concert… I tried the script at 8PM.. Too early for a plate solve I guess as it failed… Is there a way to do a retry automatically in 15 min intervals if plate solving fails due to light conditions?

 

Thanks

Dale

**Comment by rrskybox** [comment]
See Issue 15.

**Comment by astromiester1** [comment]
So, if I don't have any filters using an OSC camera, I think I do the following...

1. Options.. Pick no filter wheel.
2. Select NSW in devices tab and maker sure Clear fitler = 1, Foccus filter =0 and LRGB = 1 by default?

Or do I keep NFW unselected?

**Comment by rrskybox** [comment]
Exactly, except that Clear = 0 (you only have one index position).  I probably should add a constraint that prevents a user from configuring a Clear or Focus filter index that is not listed for that filter wheel.  The Clear and Focus filters wouldn't have to be selected, just listed.  Makes sense to me at least.

**Comment by astromiester1** [comment]
When, i make flats with my OSC, the fits default name is noFilter in the header. Is  NFW in Humanson the name given in fits for images? I know they need to matchIn order for the two to calibtate.Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 3/24/23  9:09 PM  (GMT-05:00) To: rrskybox/Humason ***@***.***> Cc: astromiester1 ***@***.***>, Author ***@***.***> Subject: Re: [rrskybox/Humason] Build 235 Observations / Recommendations (Issue #13) 
Exactly, except that Clear = 0 (you only have one index position).  I probably should add a constraint that prevents a user from configuring a Clear or Focus filter index that is not listed for that filter wheel.  The Clear and Focus filters wouldn't have to be selected, just listed.  Makes sense to me at least.

**Comment by rrskybox** [comment]
As I had feared, I guess I didn't think all this OSC thing totally through.  Normally, TSX fills a flat's fits header with the name assigned to the filter with which the image was made.   TSX must use "No Filter" when no filter wheel is installed.  I failed to consider that.

So, it seems the logical thing to do is to change "NFW" to "noFilter" to get things matched up when configuring an OSC.   Not nearly as cool, but seems harmless; let's try it.  I have to verify that "noFilter" is exactly what TSX is writing in the fits, but look for Build 239 coming out later today to get that organized.

**Comment by rrskybox** [comment]
As it turns out, if a filter wheel is not set up,  TSX does not create a FILTER field at all in the header for either flats or lights.  Presumably whatever you are reading your fits header with is returning "no filter" when it can't find that field,  "NFW" will only be found in the file **_name_** when it's stored by Humason, not in the fits header.  If you have TSX store the image, then it depends upon what you configured for the autosave -- however, ":f" won't show anything in the no filter wheel case.

So, I think we'll leave things as is for now with "NFW" as the default filter name for the no filter wheel situation.  Hopefully whatever you're using to calibrate images can sort out the situation when the fits header has no FILTER field for both lights and flats.

**Comment by astromiester1** [comment]
Hi Rick, if I use your advice as stated on SB forum regarding Focus2 autodark how will that affect using Humanson… Won’t Humanson change my reduction settings or will it use what I have listed based on your instructions below…

 

 

If it is a hot pixel problem (and that’s not unheard of), then using the “full calibration” approach described above may suffice for an OSC. You may only need a single dark at no more than 10 second exposure and let scaling handle the rest. Just make sure you take the dark at or near the camera temperature that you normally shoot. 

1. With your OSC, take one dark using the camera-cover technique that you described above, about 1 second long. Save the image. 

2. Bring up Input->Image Calibration Library. Highlight (select) “Imager” reduction group. 

3. Select “Add Frames”. In the folder window, navigate to and select the dark image that you just took. Close the window. 

4. Select Camera->Focus Tools tab. Change the calibration type to “Full Calibration”. In the associated reduction group list box , select “Imager”. Run @Focus2. 

A TSX will scale the dark to whatever exposure @Focus2 comes up with, probably good enough to get rid of your hot pixel. 

See if that helps. Admittedly, I laid this out from memory so I might have messed up the steps a bit, but you should get the idea. More information on full calibration is in the manual. 

– Rick 



**Comment by rrskybox** [comment]
Humason AutoFocus will use whatever image reduction setting is set for Focus on the Option window.  So, yes, my hot pixel work-around  would apply when using Humason as well.   This assumes, however, that somebody using an OSC might want to run full image reduction for focusing (e.g. hot pixel removal) and full image reduction for imaging, AND, use two different calibration libraries, but I don't know why one would need to.  For that, I don't have a solution right now.
