### ISSUE TITLE
Image shift during guiding question

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#14]
Hi Rick,

Curious, I do not have dither enabled when guiding but it appears my images shift left and right when using blink in Pixinsight. Do you have a dropbox I can send the images or maybe, I might make a quick video of the behavior. Could your script be forcing a guide shift during the imaging sessions. Let me know if you need any debugging from me.. Maybe, a log could be generated from the script in the future or something.

Thanks

**Comment by rrskybox** [comment]
A shift in the image frame is not unexpected upon a meridian flip or if your guider shifts guide stars mid-exposurefor some reason.  Otherwise it is curious.  If you suspect that the guider is drifting then grabbing a different guide star between images, then select the "Resync" option to reset the guider between images.   If you haven't configured it, Humason will not dither.  Dithers are only a few pixels anyway,in random directions, and the shift should not be particularly noticeable.  

You'll need to sign up for a personal dropbox to forward images or logs.  DropBox.com is pretty good.  I use OneDrive which I have to admit has some challenges.

The Humason log files are in the folder .../Humason/Logs, delineated by date.

**Comment by astromiester1** [comment]
[2023-03-06.log](https://github.com/rrskybox/Humason/files/10948762/2023-03-06.log) This is my log and it appears the guiding is normal once the imaging started... Not sure...

**Comment by astromiester1** [comment]
I will take a small movie clip while in pixinsight using blink and try an upload here or in dropbox invite.

**Comment by rrskybox** [comment]
The log indicates that you are losing the guide star because it is too dim.  Set the maximum guide star exposure to 10 and see if that helps.

**Comment by astromiester1** [comment]
Ok...Will give it a shot...

**Comment by rrskybox** [comment]
Glad to hear that it's going better.  You can make changes to all the guider fields during sequencing, but they don't get applied until the next time autoguiding is started.  This is a limitation of TSX in that once Autoguiding is turned on, you can't change the exposure length.  However, that still seems like an interesting idea so I'll look back into it (see below). 

The on-the-fly guider program was written way back when TSX didn't allow a user to manually update any parameters while autoguiding was running.  Since then, SB has added that feature to TSX so the program is minimally useful now.  I only kept it around as an example for anyone who wanted to know how to do it programmatically,

Resync causes Humason to run through the guider startup process for each image frame.  That is, recenter the target (CLS), then rerun guide star acquisition and exposure optimization (if autoguiding is enabled).  It adds 15-60 seconds to the overhead.  I originally added the Resync option to support guiderless imaging but it also works for autoguiding during changing imaging conditions, e.g. clouds moving through.

Note that because any of the guider fields can be changed during sequencing, if you selected Resync at some point, autoguiding would be stopped and restarted before the next image.  Any changed guider fields would be applied at that time.  Subsequently you could disable Resync if you were happy with the results -- that option too should be able to be changed during sequencing.

Presumably, I could modify Humason to automatically execute a one-time Resync if the user modified any of the guider exposure fields during imaging.  I have to think about that a bit, though, and consider possible collateral damage.  For now, the manual method I described above would work.

**Comment by astromiester1** [comment]
Ok...I will standbye...Thanks Rick...DaleSent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 3/15/23  10:33 AM  (GMT-05:00) To: rrskybox/Humason ***@***.***> Cc: astromiester1 ***@***.***>, Author ***@***.***> Subject: Re: [rrskybox/Humason] Image shift during guiding question (Issue #14) 
Glad to hear that it's going better.  You can make changes to all the guider fields during sequencing, but they don't get applied until the next time autoguiding is started.  This is a limitation of TSX in that once Autoguiding is turned on, you can't change the exposure length.  However, that still seems like an interesting idea so I'll look back into it (see below).
The on-the-fly guider program was written way back when TSX didn't allow a user to manually update any parameters while autoguiding was running.  Since then, SB has added that feature to TSX so the program is minimally useful now.  I only kept it around as an example for anyone who wanted to know how to do it programmatically,
Resync causes Humason to run through the guider startup process for each image frame.  That is, recenter the target (CLS), then rerun guide star acquisition and exposure optimization (if autoguiding is enabled).  It adds 15-60 seconds to the overhead.  I originally added the Resync option to support guiderless imaging but it also works for autoguiding during changing imaging conditions, e.g. clouds moving through.
Note that because any of the guider fields can be changed during sequencing, if you selected Resync at some point, autoguiding would be stopped and restarted before the next image.  Any changed guider fields would be applied at that time.  Subsequently you could disable Resync if you were happy with the results -- that option too should be able to be changed during sequencing.
Presumably, I could modify Humason to automatically execute a one-time Resync if the user modified any of the guider exposure fields during imaging.  I have to think about that a bit, though, and consider possible collateral damage.  For now, the manual method I described above would work.

**Comment by rrskybox** [comment]
After giving this some thought, I decided that the current work-around was both sufficient and safest.  That is, if you select Resync at some point, autoguiding will be stopped and restarted after the current image competes and before the next image. Any changed guider fields would be applied at that time.  If you were happy with the tracking results then, subsequently you can uncheck Resync.  Otherwise you can modify the guider fields again to improve results.   I.e. if you can't fix it, feature it.
