### ISSUE TITLE
Customizable Object Change For Different Equipment

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#6]
You mentioned your code is specifice to your setup. I guess I can search all the code for skyx telescope mount and camera objects and set accordingly. I guess that would be skyx opbject sky6RASCOMtele for the mount and ccdsoftCamera for my cameras. I have a Paramount ME and use ZWO cameras for imaging and guiding. Maybe, you can list what projects I would have to alter. I can figure it out if your busy... Anyway, enjoy your day...

Thanks
Dale

**Comment by astromiester1** [comment]
So, far if appears your objects are unconstrained to use what is selected in TSX.. Nice... Anyway, I picked some simulators in TSX and HumanOn connected to them... So far... Sweet.... I will try the real thing later today....

**Comment by astromiester1** [comment]
Get This error report. Cannot generte sequence No filters configured. I am using a OSC camera. Tried to set LRGB ratio to 0.  

HumanOn window

Updating Sequence
Disconnecting mount
Cannot sequence: No filters have been selected

Also from Nightshift Humanon log..

:39:31 A new target plan has been created for M1
15:39:41 Disconnecting mount
15:39:42 A new target plan has been created for NGC1952
15:39:50 Error: Attempted to update empty target sequence
15:39:59 Error: Attempted to update empty target sequence
15:40:44 Error: Attempted to update empty target sequence
15:41:02 Error: Attempted to update empty target sequence
15:41:24 Error: Attempted to update empty target sequence
15:41:49 Checking mount connections
15:42:37 Error: Attempted to update empty target sequence

**Comment by rrskybox** [comment]
The mount and imaging hardware that I've designed and tested on is Paramount, Optic and SBIG, but all that is abstracted inside of TSX anyway.  That said, I've always assumed a filter wheel and that's pretty integral.  In the case you have none however (e.g. OSC), there is no obvious reason why you couldn't spoof it with the SB filter wheel simulator:  Simply set the simulator up with one filter.  You can name it anything except "Filter xx".  Humason ignores any filter name starting with "Filter" in order to avoid unnecessarily listing the potentially hundreds of default filter names assigned to empty wheel slots.

To configure the filterwheel for Humason, open the Devices tab, hit Refresh and enable (check) that filter you set up.  Enter that filter number for both the Clear and Focus filters.  This should fix the error you got "Cannot sequence...".

The LRGB Ratio field in the Target tab sets the number of times the filter selected for the Clear filter is to be imaged followed by all the other filters imaged once -- for each Loop.  If you set it to 0 then no shots shot be taken at all, but I've never tried it (looks like you did).  For something like an OSC with a fake filterwheel as described above, set LRGB Ratio to 1.

**Comment by astromiester1** [comment]
I used the simulator and used devices settings in HumansOn set clear filter to 1 and focus filter to 0. In Targets I set LRGB ratio to 1. Seems to work so far...

**Comment by astromiester1** [comment]
Ok.. Ran a sequence on a test object using all simulators in TSX. This may not be a good idea to test but so far this is what happend in HumanOn... I set 10 exposures with 2 loops.  Did not see any pics stored..

First try I get a Limites exceeded error Error=218 then tried again and 
looks like it gags when it trys to select filter.. I get a error in skyx saying command failed Error=206

I tried both filter simulator ASCOM and SBIG and both give me the Error = 206 and shuts down the script. I think the 206 error is a device connection error... Anyway, I will try some real devices today to see what happens.. Did you ever try testing your code with simulators in TSX? Wonder what you used if you did...  Logs below if you wanted to see them..


Disconnecting mount
********* New Humason Run **********

* Humason V4.0.0.231  2/13/2023 **

******* Humason Initialized ********
Disconnecting mount
A new target plan has been created for M1
Disconnecting mount
Updating Sequence
Disconnecting mount
Sequence Updated
Updating Sequence
Disconnecting mount
Sequence Updated
Connecting
Connecting mount
Connecting camera
Connecting guide camera
Connecting focuser
Devices Connected
Running diagnostics
Diagnostics success
Loading first session target plan
Waiting until 14:51
Waiting until 14:51
Initializing system
Connecting
Connecting mount
Connecting camera
Connecting guide camera
Connecting focuser
Devices Connected
Checking for new target to clear meridian
New target is clear of meridian
 ******************* Imaging Target: M1
Disconnecting mount
Initiating coordinate CLS to M1
Unparking mount for CLS, if needed
Initial Slew Completed
CLS Error: Limits exceeded. Error = 218.
CLS Failed: Error 218 -- trying again
Unparking mount for CLS, if needed
Initial Slew Completed
CLS Error: Limits exceeded. Error = 218.
CLS Failed: 218
Aborting and Closing Down
Parking Mount
Disconnecting all devices
Aborting guiding
Shutting down guider temperature regulation, if any
Disconnecting guider
Disconnecting focuser
Aborting imaging
Turning off camera temperature regulation
Disconnecting camera
Disconnecting mount
All TSX devices disconnected
Abort Completed -- awaiting new orders, Captain

2nd attempt......My comment....

Running diagnostics
Diagnostics success
Loading first session target plan
Waiting until 15:02
Waiting until 15:02
Initializing system
Connecting
Connecting mount
Connecting camera
Connecting guide camera
Connecting focuser
Devices Connected
Checking for new target to clear meridian
New target is clear of meridian
 ******************* Imaging Target: M1
Disconnecting mount
Initiating coordinate CLS to M1
Unparking mount for CLS, if needed
Initial Slew Completed
CLS Error: Error: command failed. Error = 206.
CLS Failed: Error 206 -- trying again
Unparking mount for CLS, if needed
Initial Slew Completed
CLS Error: Error: command failed. Error = 206.
CLS Failed: 206
Aborting and Closing Down
Parking Mount
Disconnecting all devices
Aborting guiding
Shutting down guider temperature regulation, if any
Disconnecting guider
Disconnecting focuser
Aborting imaging
Turning off camera temperature regulation
Disconnecting camera
Disconnecting mount
All TSX devices disconnected
Abort Completed -- awaiting new orders, Captain

**Comment by astromiester1** [comment]
Ok... Tried real equipment... It seems to work.. It tried to plate solve but I had cover on scope.. So, good news...

One thing that I thought was weird though... It connects and disconnects the scope 3 times before actually slewing to target and trying to image...

The HumanOn log is below...

Disconnecting mount
Disconnecting mount
********* New Humason Run **********

* Humason V4.0.0.231  2/13/2023 **

******* Humason Initialized ********
Cannot sequence: No filters have been selected
Cannot sequence: No filters have been selected
Disconnecting mount
Cannot sequence: No filters have been selected
Disconnecting mount
Updating Sequence
Disconnecting mount
Cannot sequence: No filters have been selected
Sequence Updated
Updating Sequence
Disconnecting mount
Cannot sequence: No filters have been selected
Sequence Updated
Updating Sequence
Disconnecting mount
Cannot sequence: No filters have been selected
Sequence Updated
Cannot sequence: No filters have been selected
Cannot sequence: No filters have been selected
Disconnecting mount
A new target plan has been created for IC1805
Updating Sequence
Cannot sequence: No filters have been selected
Cannot sequence: No filters have been selected
Disconnecting mount
Cannot sequence: No filters have been selected
Sequence Updated
Updating Sequence
Disconnecting mount
Sequence Updated
Updating Sequence
Disconnecting mount
Sequence Updated
Running diagnostics
Diagnostics success
Loading first session target plan
Waiting until 16:36
Waiting until 16:36
Initializing system
Connecting
Connecting mount
Connecting camera
Connecting guide camera
Connecting focuser
Devices Connected
Checking for new target to clear meridian
New target is clear of meridian
 ******************* Imaging Target: IC 1805
Disconnecting mount
Initiating coordinate CLS to IC 1805
Unparking mount for CLS, if needed
Initial Slew Completed
CLS Error: The astrometric solution failed. Error = 655.
CLS Failed: Error 655 -- trying again
Unparking mount for CLS, if needed
Initial Slew Completed
CLS Error: The astrometric solution failed. Error = 655.
CLS Failed: 655
Aborting and Closing Down
Parking Mount
Disconnecting all devices
Aborting guiding
Shutting down guider temperature regulation, if any
Disconnecting guider
Disconnecting focuser
Aborting imaging
Turning off camera temperature regulation
Disconnecting camera
Disconnecting mount
All TSX devices disconnected
Abort Completed -- awaiting new orders, Captain

**Comment by rrskybox** [comment]
Looks like you're making progress.  

> Did you ever try testing your code with simulators in TSX? Wonder what you used if you did.

Yes, I used the simulators quite a bit when I was developing this a number of years ago.  However, the simulators become almost useless when dealing with rotation, focusing, autoexposure and autoguiding, which are the real challenges with automagic sequencing.   Simulators also blow up on simple things like trying to regulate camera temperature.  You spend more time building work-arounds for the limitations of the simulators than useful code.  And, I swear I tried them all -- some work better than others depending on the situation.  Of course, real hardware is best but you generally need dark and clear skies as well.

> It connects and disconnects the scope 3 times before actually slewing to target and trying to image...

Don't worry about the multiple mount connect/disconnects.  Some of that is diagnostic and some is because odd stuff going on inside TSX that I've never gotten around to finding better work-arounds.  

Just as a note, getting both the plate solving (Image Link) and, if you are using it, autofocus and autoguide configuration dialed in before trying to run Humason will save a lot of headaches.

**Comment by rrskybox** [comment]
There is one thing I should mention w/r to Plate Solves and CLS.   One of the changes that SB made over the past year or so was to require that a pixel scale is set for any scripted image link, including a CLS, even if Blind solving.  Rather than make the image scale a Humason configuration parameter, I chose to automatically pull it out of the TSX FOVI definitions.  Humason will scan the FOVI definitions for the currently active FOV and pull the scale from that.  So, this is another thing that you have to have set up even with the simulators.  I'll have to look to see if I documented that in the user guide, but there ya go.
