### ISSUE TITLE
If Autoguider fails calibration, the script continues to do imaging sequence

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#9]
I noticed the y calibration failed but the script continued to image anyway.

Fyi, I noticed focuser 2 works alot better than 3. That part work very nice... I have Optec TCFs.

**Comment by astromiester1** [comment]
This mount Im trying this on does not supprot direct guide but instead uses pulse guide. That could be what is causing the guider cal failure. I don't get an error in TSX but you can tell the mount is not moving when it trys to calibrate. Normally, TSX will give you a message saying Direct guide not supported on this mount... In this case using a Losmandy G11T.  I will try on my ME tommorrow night just the same, but I would like to be able to select either pulse guide or direct guide. Maybe,  just rely on settings user selects in TSX. Not sure...

**Comment by rrskybox** [comment]
I've always preferred @Focus2 over 3 for my Optic focuser(s).  Humason refocuses every degree, if enabled.  You're rarely very far off the critical region even if the temperature is changing rapidly and you miss one because of clouds.  And, it only takes a minute or so.   I don't know if it is, but @Focus3 always just feels slow.  Some folks love it though.

I'll have to check, but I think my idea was that if calibration failed then autoguiding should not be turned on but imaging would continue, at least until the next opportunity (end of loop) to calibrate and turn back on.  My theory was that I occasionally have clouds or such roll through that killed the calibration but I didn't want to stop imaging.   Properly prepared with T-Point, the Paramounts have outstanding guiderless tracking and I didn't want to shut down unnecessarily.  Anyway, that's the theory.

I've never really trusted Pulse Guide.  I think either Relays (non-Paramount) or Direct Guide (Paramount) are the best way to go.  I used relays on my Gemini.  It did have a bit of a backlash problem, as I recall though.  That could be an issue for you as well.

**Comment by rrskybox** [comment]
Oh, should also say that Humason doesn't (can't) change the guider type (Relays, Pulse or Direct).  Those have to be set in TSX.  Humason will allow you to adjust the duration of each axis calibration in the Guider tab -- seconds for Relays, arcsec for Direct.  That is just to make it easier to play with them until you get it right.  Inside TSX you have to keep bouncing back and forth between windows and tabs just to test calibration set ups.  I found that annoying.
